### ISSUE TITLE
Race condition between application code and import map overrides

### ISSUE THREAD

**Issue by brandones** [joeldenning/import-map-overrides#48]
I've got some initialization code that depends on import map overrides being loaded. Is there a way to have my code run as soon as import map overrides are loaded, but not before? A Promise I can `then`? I tried listening on `import-map-overrides:change` and that doesn't seem to get triggered with the initial load. See the following:

```js
let didInitialCheck = false;
function checkForFile() {
  setTimeout(() => {
    if (!didInitialCheck && typeof System !== "undefined") {
      try {
        console.log("initial", System.resolve("config-file"));
      } catch (e) {
        console.log("initial: not resolved");
      }
      didInitialCheck = true;
    } else {
      checkForFile();
    }
  }, 5);
}
checkForFile();

window.addEventListener(
  "import-map-overrides:change",
  () => { console.log("import-map-overrides:change"); console.log("change", System.resolve("config-file")); }
);

setTimeout(() => { console.log("timeout", System.resolve("config-file"))}, 1000);
```

Logs 
![Screenshot from 2021-01-21 20-07-41](https://user-images.githubusercontent.com/1031876/105445259-5df75380-5c24-11eb-9ca5-383ccae8883a.png)

**Comment by joeldenning** [comment]
This should work:

```html
<script id="imo" src="https://cdn.jsdelivr.net/npm/import-map-overrides/dist/import-map-overrides.min.js"></script>
```

```js
document.querySelector('#imo').addEventListener('load', () => {
  console.log('import-map-overrides finished initializing')
})
```

**Comment by brandones** [comment]
Unfortunately `document.querySelector('#imo')` returns null at the time this code is running. I could use a MutationObserver but it seems like there should be an easier way?

**Comment by joeldenning** [comment]
Ah so the javascript you're running is executed before the `<script>` is put on the page then. In that case, sure I can add an event for this.

**Comment by joeldenning** [comment]
Fix released in https://github.com/joeldenning/import-map-overrides/releases/tag/v2.3.0. Here's the documentation for it: https://github.com/joeldenning/import-map-overrides/blob/master/docs/api.md#init

**Comment by brandones** [comment]
Awesome, thank you Joel!

**Comment by brandones** [comment]
Something is still not all the way there at the time `init` is called.

```js
window.addEventListener("import-map-overrides:init", () => {
  console.log("init");
  check();
});

setTimeout( () => {
  console.log("200ms");
  check();
}, 200);

function check() {
  try {
    console.log("config file: ", System.resolve("config-file"));
  } catch (e) {
    console.log("config file not resolved");
  }
}
```

![Screenshot from 2021-01-23 21-51-24](https://user-images.githubusercontent.com/1031876/105622294-3390cc00-5dc5-11eb-9b24-c39e58d36a71.png)

**Comment by joeldenning** [comment]
A couple things that could explain this:

1. SystemJS hasn't finished parsing all import maps yet. If you have a separate an external map downloaded over the network, that could cause systemjs to wait before applying the import map from import-map-overrides. You can use `System.prepareImport()` to wait for it.
2. You're expecting `importMapOverrides.addOverride()` to apply without reloading the page. A page reload is currently required after applying an override.

For 1, try the following:

```js
window.addEventListener("import-map-overrides:init", () => {
  System.prepareImport().then(() => {
    console.log('url', System.resolve('config-file'));
  })
});
```

One thing I'd do to debug is go to the Elements tab in the browser devtools and verify whether you can find `<script id="import-map-overrides" type="systemjs-importmap"></script>`. If so, verify its contents include `config-file`

**Comment by brandones** [comment]
Okay, I think it was (1)! I'm using that code and now getting a new and different error message.

```
Problem importing config-file TypeError: registration[1] is not a function
(anonymous) @ module-config.ts:147
 ...
system.js:318 Uncaught (in promise) TypeError: registration[1] is not a function
    at system.js:318
```

This is the same message I get with the following code:

```js
setTimeout( () => {
  check();
}, 50);

function check() {
  let found;
  try {
    found = System.resolve("config-file")
    console.log("config file: ", found);
  } catch (e) {
    console.log("config file not resolved");
  }
  if (found) {
    System.import("config-file").then(file => {
      console.log("contents: ", file.default);
    });
  }
}
```

Where that timeout value is anywhere from the time it takes to download `config-file` *n* up to about *n+50ms*. The error is produced intermittently—the smaller the timeout, the more likely it is to come up.

Maybe this has something to do with named registers, as in the [SystemJS issue](https://github.com/systemjs/systemjs/issues/2185) you've worked on?

**Comment by joeldenning** [comment]
To help you understand the `registration[1] is a not a function` error, I'll define what `registration` is. The `registration` object is the array of arguments passed to `System.register()`.

Generally, build tools (including webpack) will produce a bundle that looks like this:

```js
System.register(['react', 'react-dom'], function () {}))
```

In the above bundle, the registration array is the following:

```js
[['react', 'react-dom'], function () {}]
```

The first item in the registration array is an array of dependencies. The second item is the function containing the code for your module.

So going back to `registration[1] is not a function` - this means that the second item in the array is not a function like it should be.

A common reason why this can happen is that a lot of build tools, including webpack and typescript, will output the following if configured to do so:

```js
System.register('library-name', ['dep1'], function () {});
```

In that case, the second item in the registration array is `['dep1']` which is not a function like SystemJS expects. The named-register.js SystemJS extra modifies the registration array by removing the string `'library-name'` so that the remaining items correctly match what SystemJS core expects.

Other SystemJS extras can also impact the registration array. For example, the amd.js SystemJS extra converts a call to `define()` into a registration array.

To diagnose the cause of the problem in your case, I'd set a break point where the error is occuring, and inspect the `registration` array. If it has three items instead of two, due to a string name, then the named-register extra might help. If it only has two items, but they are not an array of deps + function, then I'd figure out which module's registration array you're looking at (the `load` object in the devtools will help you see that) and then try to figure out why the registration array is wrong. In doing so, you might come across the `getRegister()` function within SystemJS - that is the function called within SystemJS core which must return the registration array. Generally the script-load.js file is where `getRegister()` is invoked.

**Comment by brandones** [comment]
Wow, thank you so much for such a thorough explanation. I'll look into it.
